name: "multi event / workflow"

on:
    push:      #event
        branches:
            - master
            - test
    pull_request:
        branches:
            - master

jobs:
    on-push:
        runs-on: ubuntu-latest
        steps:
            - name: "running on master/test push"
              run: echo "running on master/test push"
    
    on-pull-request:
        runs-on: ubuntu-latest
        steps:
            - name: "running on pull request"
              run: echo "running on the pull request"

